### ISSUE TITLE
Edge configurations

### ISSUE THREAD

**Issue by Simoneu01** [ecrmnn/express-edge#1]
Hi!

Thanks you for this package!!!

Can i configure edge? (https://edge.adonisjs.com/docs/getting-started)

![image](https://user-images.githubusercontent.com/43807696/60895414-ea217000-a264-11e9-86da-6fc9140646bd.png)

`const edge = require('edge.js')
edge.configure({
  cache: process.env.NODE_ENV === 'production'
})`

**Comment by ecrmnn** [comment]
Hi @Simoneu01 
I don't have time to work on this right now.
Feel free to submit a PR.

**Comment by Simoneu01** [comment]
@ecrmnn 
See this fork of @puuga

https://github.com/puuga/express-edge

**Comment by puuga** [comment]
@Simoneu01 Do you still need it? If yes, I will submit the PR.

**Comment by puuga** [comment]
@Simoneu01 Just make the #2 PR.

**Comment by ecrmnn** [comment]
Closed in https://github.com/ecrmnn/express-edge/commit/0675b024f336c7c8f3077a19c61036c62068dec5
